services:
  app:
    container_name: ${APP_NAME}-app
    build: ./docker/php
    hostname: app
    volumes:
      - ./laravel-src/:/var/www/html
    environment:
      - APP_NAME=${APP_NAME}
      - APP_URL=${APP_URL:-http://localhost:8080}
      - APP_ENV=${APP_ENV:-local}
      - DB_CONNECTION=mysql
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-app_db}
      - DB_USERNAME=${DB_USERNAME:-user}
      - DB_PASSWORD=${DB_PASSWORD:-password}

  web:
    container_name: ${APP_NAME}-web
    build: ./docker/nginx
    ports:
      - ${WEB_PORT:-8080}:80
    depends_on:
      - app
    volumes:
      - ./laravel-src/:/var/www/html
      - ./docker/nginx/ssl:/etc/nginx/ssl
    environment:
      - PHP_APP_HOST=app
    command: /bin/sh -c "envsubst '$$PHP_APP_HOST' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  mysql:
    container_name: ${APP_NAME}-mysql
    build: ./docker/mysql
    hostname: ${DB_HOST:-db}
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      TZ: "UTC"
      MYSQL_DATABASE: ${DB_DATABASE:-app_db}
      MYSQL_USER: ${DB_USERNAME:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - ./docker/mysql/db/data:/var/lib/mysql
      - ./docker/mysql/conf:/etc/mysql/conf.d
      - ./docker/mysql/db/logs:/var/log/mysql
